// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureLink.Api.Infrastructure.Data;

#nullable disable

namespace SecureLink.Api.Migrations
{
    [DbContext(typeof(FileShareDbContext))]
    partial class FileShareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureLink.Api.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SecureLink.Api.Core.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnonymousDownload")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowAnonymousView")
                        .HasColumnType("boolean");

                    b.Property<bool>("BurnAfterDownload")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinHash")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Files_ExpiresAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Files_Name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Files_ParentId");

                    b.HasIndex("BurnAfterDownload", "IsAccessed")
                        .HasDatabaseName("IX_Files_BurnAfterDownload_IsAccessed");

                    b.HasIndex("OwnerId", "IsArchived")
                        .HasDatabaseName("IX_Files_OwnerId_IsArchived");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SecureLink.Api.Core.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnonymousDownload")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowAnonymousUpload")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowAnonymousView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinHash")
                        .HasColumnType("text");

                    b.Property<string>("ShareToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Folders_ExpiresAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Folders_Name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Folders_ParentId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Folders_ShareToken")
                        .HasFilter("\"ShareToken\" IS NOT NULL");

                    b.HasIndex("OwnerId", "IsArchived")
                        .HasDatabaseName("IX_Folders_OwnerId_IsArchived");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("SecureLink.Api.Core.Entities.TextSnippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BurnAfterRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_TextSnippets_ExpiresAt");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_TextSnippets_OwnerId");

                    b.ToTable("TextSnippets");
                });
#pragma warning restore 612, 618
        }
    }
}
